# Site settings
title: Dominica
client:
  name: Discover Dominica
  link: "https://discoverdominica.com/en"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Dominica is an island of outstanding – if not unmatched – natural beauty. The coast defies convention with dramatic outcrops and pebble beaches. Inland you’ll find remarkable natural phenomena, from the Boiling Lake to the Champagne Reef.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/dominica" # the subpath of your site, e.g. /blog/
img:     "/dominica/_assets/img"
css:     "/dominica/_assets/css"
js:      "/dominica/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed